name: Linux Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Download Dependencies
      run: |
           sudo apt-get install libxkbcommon-x11-0 -y
           sudo apt install libgl1-mesa-dev -y
    - name: Download Qt
      run: |
           cd $GITHUB_WORKSPACE
           wget http://qt.mirror.constant.com/archive/qt/5.13/5.13.1/qt-opensource-linux-x64-5.13.1.run -O ./qt-install.run
    - name: Install Qt
      run: |
           cd $GITHUB_WORKSPACE
           chmod +x ./qt-install.run
           ./qt-install.run --script ./actions/installer-noninteractive-linux.qs --verbose --platform minimal
    - name: Build Anthem and generate Appimage
      run: |
           cd $GITHUB_WORKSPACE
           export PATH=$PATH:/qt/5.13.1/gcc_64/bin/
           qmake ./Prototyping.pro CONFIG+=release PREFIX=/usr
           make -j$(nproc)
           wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage -O ./linuxdeployqt.AppImage
           sudo chmod a+x ./linuxdeployqt.AppImage
           ./linuxdeployqt.AppImage ./Main/appdir -appimage
           ls