name: Linux Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Download Dependencies
      run: |
           sudo apt-get install libxkbcommon-x11-0 -y
           sudo apt install libgl1-mesa-dev -y
    - name: Download Qt
      run: |
           cd $GITHUB_WORKSPACE
           wget http://qt.mirror.constant.com/archive/qt/5.13/5.13.1/qt-opensource-linux-x64-5.13.1.run -O ./qt-install.run
    - name: Install Qt
      run: |
           cd $GITHUB_WORKSPACE
           chmod +x ./qt-install.run
           ./qt-install.run --script ./actions/installer-noninteractive-linux.qs --verbose --platform minimal
    - name: Build Anthem and generate Appimage
      run: |
           cd $GITHUB_WORKSPACE
           export PATH=$PATH:/qt/5.13.1/gcc_64/bin/
           qmake ./Prototyping.pro CONFIG+=release PREFIX=/usr
           make INSTALL_ROOT=appdir -j$(nproc) install
           wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
           chmod a+x linuxdeployqt-continuous-x86_64.AppImage
           mv linuxdeployqt-continuous-x86_64.AppImage $GITHUB_WORKSPACE/Main/appdir/opt/
           cd $GITHUB_WORKSPACE/Main/appdir/opt/
           mkdir -p ./Main/{lib,share/{applications,icons/hicolor/256x256/apps}}
           mv ../../../anthem.desktop ./Main/share/applications/
           mv ../../../Anthem.png ./Main/share/icons/hicolor/256x256/apps/
           ./linuxdeployqt-continuous-x86_64.AppImage ./Main/share/application/*.desktop -appimage
           sudo find / -name "*anthem*"