name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download repository
      run: git clone --single-branch --branch jake-dev https://github.com/SecondFlight/daw-prototype.git
    - name: Download Qt
      run: wget http://qt.mirror.constant.com/archive/qt/5.13/5.13.0/qt-opensource-linux-x64-5.13.0.run
    - name: Install Dependencies
      run: sudo apt-get install -y libx11-xcb-dev libglu1-mesa-dev
    - name: Install Qt       
      run: .\qt-opensource-linux-x64-5.13.0.run --script .\daw-prototype\actions\installer-noninteractive.qs --platform minimal
    - name: Find qmake
      run: find / -name "qmake"
    - name: Build Anthem
      run: |
           mkdir build
           cd build 
           qmake ../daw-prototype/Prototyping.pro
           make
