name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download Repo
      run: git clone --single-branch --branch jake-dev https://github.com/SecondFlight/daw-prototype.git
    - name: Download Qt
      run: wget http://download.qt.io/official_releases/qt/5.13/5.13.0/qt-opensource-linux-x64-5.13.0.run
    - name: Change Permissions
      run: chmod +x ./qt-opensource-linux-x64-5.13.0.run
    - name: Install Qt       
      run: ./qt-opensource-linux-x64-5.13.0.run --script ./daw-prototype/actions/installer-noninteractive.qs --platform minimal
    - name: Build Anthem
      run: mkdir ./build
           cd ./build 
           qmake ../daw-prototype/Prototyping.pro
           make
