name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download repository
      run: git clone --single-branch --branch jake-dev https://github.com/SecondFlight/daw-prototype.git
    - name: Download Qt
      run: |
            curl -s -o null http://download.qt.io/official_releases/qt/5.13/5.13.0/qt-opensource-windows-x86-5.13.0.exe
            dir
    - name: Install Qt       
      run: .\qt-opensource-windows-x86-5.13.0.exe --script .\daw-prototype\actions\installer-noninteractive.qs --platform minimal
    - name: Show Qt directory
      run: dir c:/Qt
    - name: Build Anthem
      run: |
           mkdir build
           cd build 
           qmake ../daw-prototype/Prototyping.pro
           make
